# Generated by Django 5.2.4 on 2025-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="Digite aqui o texto da pergunta.",
                        verbose_name="Pergunta",
                    ),
                ),
                (
                    "answer",
                    models.TextField(
                        help_text="Digite aqui o texto da resposta.",
                        verbose_name="Resposta",
                    ),
                ),
            ],
        ),
    ]
